# moralnet config.yml
project: moralnet
topology:
  family: small_world # always required
  connected: true # always required?
  directed: false # always required?
  inputs: # must be the chosen family's required inputs
    n: 16
    k: 5
    p: 0.3
  conditions:
    omega: [0.4, 0.6] # range for small worldness relative to real world networks
    degree: [3, 5] # range of connections any node should have
    rounds: 5
    repeats: false
    subgraphs: 2
