name: Generate Network Topologies

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10 #TODO: Make .env based
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute generator via main py script
        run: |
          python studies/generate.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Network topologies genated by GitHub Actions"
          git push